# generated by gen_formats.py
# do not edit

format_for_extension = {'yaml': 'bibyaml', 'bib': 'bibtex', 'bibtexml': 'bibtexml'}

extension_for_format = {'bibtex': 'bib', 'bibyaml': 'yaml', 'bibtexml': 'bibtexml'}
