#!/usr/bin/env python

import sys
import optparse
import pybtex
from os import path

def main():
    opt_parser = optparse.OptionParser(prog='pybtex', usage='%prog auxfile[.aux] [options]', version='%%prog-%s' % pybtex.__version__)
    opt_parser.add_option('-f', '--bibliography-format', action='store', type='string', dest='bib_format', default='bibtex')
    opt_parser.add_option('-b', '--output-backend', action='store', type='string', dest='output_backend', default='latex')
    encoding = opt_parser.add_option_group('encoding options')
    encoding.add_option('--bibtex-encoding', action='store', type='string', dest='bib_encoding')
    encoding.add_option('--latex-encoding', action='store', type='string', dest='latex_encoding')

    (options, args) = opt_parser.parse_args()

    if not args:
        opt_parser.print_help()
        sys.exit(1)

    filename, ext = path.splitext(args[0])
    if not ext:
        ext = path.extsep + 'aux'
    pybtex.make_bibliography(filename + ext,
            bib_format=options.bib_format,
            bib_encoding=options.bib_encoding,
            latex_encoding=options.latex_encoding,
            output_backend=options.output_backend
    )

if __name__ == '__main__':
    main()
