#!/usr/bin/env python

import sys
import optparse
import pybtex
from os import path

def main():
    opt_parser = optparse.OptionParser(prog='pybtex', usage='%prog auxfile[.aux] [options]', version='%%prog-%s' % pybtex.__version__)
    opt_parser.add_option('-f', '--bibliography-format', action='store', type='string', dest='bib_format', default='bibtex')
    opt_parser.add_option('--input-charset', action='store', type='string', dest='input_charset')
    (options, args) = opt_parser.parse_args()

    if not args:
        opt_parser.print_help()
        sys.exit(1)

    filename, ext = path.splitext(args[0])
    if not ext:
        ext = path.extsep + 'aux'
    pybtex.make_bibliography(filename + ext,
            bib_format=options.bib_format
    )

if __name__ == '__main__':
    main()
